#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '
# >>> BEGIN ADDED BY CNCHI INSTALLER
EDITOR=/usr/bin/nvim
# <<< END ADDED BY CNCHI INSTALLER

if [[ $LANG = '' ]]; then
    export LANG=en_US.UTF-8
fi
